naam = input('Hallo, wat is je naam? ')
leeftijd = int(input(f'Goedendag {naam}, hoe oud ben je? '))
fav_eten = input(f'En als {leeftijd} jarige, wat eet je het liefst? ')
drinken = input(f'En wat drink je het liefst bij {fav_eten}? ')
print(f'\nDe {leeftijd} jarige {naam} drinkt het liefst {drinken} bij {fav_eten}')